core: ardupilot-manager: Add support for UDP Server endpoints on MavlinkRouter
bluerobotics/companion-docker pull request #256
Opened 2021-05-19 19:22 UTC by rafaellehmkuhl

Fix #255

2021-05-20 19:45 UTC, rafaellehmkuhl commented
Mypy is failing to understand that the connection_type argument is of type EndpointType, and not str. For that i'm ignoring type-check on the lambda line.

Related issues:

https://github.com/python/mypy/issues/8722
https://github.com/python/mypy/issues/2416

2021-05-20 20:08 UTC, patrickelectric requested changes

2021-05-20 20:08 UTC, patrickelectric commented on core/services/ardupilot_manager/mavlink_proxy/MAVLinkRouter.py
> +        types_order = {
A comment about why the order is important shoud be added here since this is not a clear thing.

2021-05-20 20:08 UTC, patrickelectric commented on core/services/ardupilot_manager/mavlink_proxy/test_all.py
> +    ]
We should also test multiple and different orders of endpoints, such as:
`udpin, udpout, udpin, tcpout, tcpin`
`udpout, udpin, tcpout, tcpin, udpin`
`udpin, tcpout, tcpin, udpin, udpout` and etc

2021-05-21 21:24 UTC, patrickelectric approved these changes

2021-05-21 21:25 UTC, merged