core: Random fixes around ardupilot_manager
bluerobotics/companion-docker pull request #300
Opened 2021-06-02 14:51 UTC by patrickelectric

2021-06-02 15:02 UTC, rafaellehmkuhl requested changes
Python's map require a callable for the first argument. It can be a regular function or a lambda.
I don't think, though, that the lambda version get's any better than the list comprehension. If fact it gets much less readable, while the regular function adds 3 lines of code.

2021-06-02 15:04 UTC, patrickelectric commented
> Python's map require a callable for the first argument. It can be a regular function or a lambda.
> I don't think, though, that the lambda version get's any better than the list comprehension. If fact it gets much less readable, while the regular function adds 3 lines of code

```
class A:
    def a(self):
        return "potato"
        
a_list = [A(), A()]

print(list(map(A.a, a_list)))
```

2021-06-02 15:07 UTC, Williangalvani commented
I honestly prefer reading list comprehensions

2021-06-02 15:31 UTC, patrickelectric commented on core/services/ardupilot_manager/mavlink_proxy/Endpoint.py
> +    def as_dict(self) -> Dict[str, Any]:
I was unable to find such function in pydantic.

2021-06-02 16:26 UTC, rafaellehmkuhl commented on core/services/ardupilot_manager/ArduPilotManager.py
> +        self.configuration["endpoints"] = list(map(Endpoint.asdict, endpoints))
Ok, just realized you're not calling the function. My mistake.

2021-06-02 16:27 UTC, rafaellehmkuhl approved these changes

2021-06-02 16:28 UTC, rafaellehmkuhl commented
Curiosity: how did you fix the mypy complaints?

2021-06-02 16:57 UTC, patrickelectric commented
> Curiosity: how did you fix the mypy complaints?

as @Williangalvani suggestion, it appears that a non static function is necessary to iterate over a inheritance class.

2021-06-03 19:58 UTC, Williangalvani approved these changes

2021-06-03 19:59 UTC, merged