Rent a new linter
bluerobotics/companion-docker pull request #402
Opened 2021-08-09 19:57 UTC by rafaellehmkuhl

Uses vue/recommended + vue/airbnb rules on Eslint

I did the necessary changes on the main frontend files to comply to the new rules.
There are several changes needed on the old/dev frontend that I still need to make, but I'm already opening the PR so you can review the structure.

2021-08-09 21:36 UTC, patrickelectric requested changes
@rafaellehmkuhl it appears that CI is failing.

2021-08-09 21:39 UTC, rafaellehmkuhl commented
> @rafaellehmkuhl it appears that CI is failing.

Yes. It's failing on the development frontend. I'm finishing the fix on those.

2021-08-09 22:00 UTC, rafaellehmkuhl commented
@patrickelectric just finished those. I will test the frontends to see if nothing was broken during the lint fixes.

2021-08-09 22:20 UTC, patrickelectric approved these changes

2021-08-09 22:33 UTC, rafaellehmkuhl commented
Just tested the frontends. There was a small bug I had introduced on the versionchooser interface, making it not show the entire repo name up, but its now fixed.

2021-08-10 14:27 UTC, Williangalvani approved these changes

2021-08-10 14:27 UTC, rafaellehmkuhl commented on core/services/versionchooser/frontend/index.html
> +      filters: {
[This one](https://eslint.vuejs.org/rules/order-in-components.html)

2021-08-10 14:27 UTC, merged