Camera manager on frontend
bluerobotics/companion-docker pull request #480
Opened 2021-09-20 13:36 UTC by rafaellehmkuhl

- Show list of available video devices;
- Show list of available video streams per device;
- Allow creating new video stream for given device;
- Allow configuration of video device controls;
- Allow deleting available video streams;
- Allow viewing video stream details.

Includes UDP stream endpoint validation.

Completely solves #447

2021-09-22 14:42 UTC, patrickelectric requested changes
Some UI chages are necessary and I'm unable to see the video locally, it also appears that there is a problem on the frontend when a h264 video is created.
![2021-09-22_11-42](https://user-images.githubusercontent.com/1215497/134365320-dc13323f-739b-4ec0-b6e4-fe0cba3cc3d1.png)

2021-09-22 14:42 UTC, patrickelectric commented on core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
> +      return this.selected_format.sizes.map((size) => ({
We should also sort it by size to start with the highest resolution

2021-09-22 14:42 UTC, patrickelectric commented on core/frontend/src/components/video-manager/VideoStreamCreationDialog.vue
> +            label="Stream endpoint"
This should have a default value for udp://0.0.0.0:5600

2021-09-22 14:42 UTC, patrickelectric commented on core/frontend/src/components/video-manager/StreamDetailsDialog.vue
> +      <div class="d-flex flex-no-wrap align-center justify-space-between">
This card misses what is the encode type

2021-09-22 14:42 UTC, patrickelectric commented on core/frontend/src/components/video-manager/VideoControlsDialog.vue
> +      <v-card-text class="d-flex flex-column">
This also needs a sets to default method to set all values to the default

2021-09-22 14:42 UTC, patrickelectric commented on core/frontend/src/components/video-manager/VideoStream.vue
> +          View details
I think that this defails card is not necessary, we can have all the information on the main card:
![2021-09-22_11-38](https://user-images.githubusercontent.com/1215497/134364694-f80f7552-f4ea-4bfc-a23a-d3f4ba25a57a.png)

2021-09-22 14:44 UTC, patrickelectric commented
We should also add a more information button, like the wifi, to have the full information about the camera capabilities if possible. 
![2021-09-22_11-43](https://user-images.githubusercontent.com/1215497/134365628-af3770d6-19c5-4b88-a45d-6d13947e5128.png)

2021-09-23 21:09 UTC, patrickelectric requested changes
Sizes are not sorted
![image](https://user-images.githubusercontent.com/1215497/134583670-218e4aca-3b3a-495a-89d8-757dd02fb1af.png)

The layout is weird
![image](https://user-images.githubusercontent.com/1215497/134583777-9a9d2936-8c3b-462e-a8cb-397876e9bd3b.png)


Details is not opening a popup when using fake source
Restaure defaults works for some but not for others, it's a bit weird, needs to click multiple times

2021-09-24 12:57 UTC, rafaellehmkuhl commented
@patrickelectric they are sorted but reversed :smile:

2021-09-24 13:24 UTC, Williangalvani commented
Can we get an "edit stream" option here?
![image](https://user-images.githubusercontent.com/4013804/134681682-9c6228ae-fb30-4322-b991-533e489a5ff7.png)

2021-09-24 13:27 UTC, rafaellehmkuhl commented
> We should also add a more information button, like the wifi, to have the full information about the camera capabilities if possible.
> ![2021-09-22_11-43](https://user-images.githubusercontent.com/1215497/134365628-af3770d6-19c5-4b88-a45d-6d13947e5128.png)

It's a cool idea. I've opened #495 to track this future change.

2021-09-24 16:09 UTC, patrickelectric approved these changes

2021-09-24 17:32 UTC, patrickelectric commented
> Can we get an "edit stream" option here?

#495

2021-09-24 17:32 UTC, merged