core: Support disabling mavlink endpoints
bluerobotics/companion-docker pull request #696
Opened 2021-12-07 23:29 UTC by rafaellehmkuhl

- Add 'enabled' property to mavlink endpoints, so they can be disabled (not used by the mavlink router) without being deleted
- Allow users to enable/disable endpoints on the fly with the endpoint frontend

With this change, the default GCS Link was duplicated, so we have a server one and a client one (with the former pointing to 192.168.2.1). The client endpoint is disabled by default. This change will make the life of our clients experiencing connection problems easier.

Fix #657

2021-12-08 16:08 UTC, rafaellehmkuhl commented on core/frontend/src/components/autopilot/EndpointCard.vue
> +      fab: false,
FloatingActionButton, but I will find a better name 😅

2021-12-08 17:12 UTC, Williangalvani commented
I think you just did :eyes:

On Wed, Dec 8, 2021, 13:09 Rafael Araujo Lehmkuhl ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In core/frontend/src/components/autopilot/EndpointCard.vue
> <https://github.com/bluerobotics/companion-docker/pull/696#discussion_r765008674>
> :
>
> > @@ -107,6 +145,8 @@ export default Vue.extend({
>
>    data() {
>
>      return {
>
>        userFriendlyEndpointType,
>
> +      fab: false,
>
>
> FloatingActionButton, but I will find a better name 😅
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/bluerobotics/companion-docker/pull/696#discussion_r765008674>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA6T53DURBRCUEWNIYNFP4LUP57KLANCNFSM5JSNYQSA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-09 10:27 UTC, patrickelectric requested changes

2021-12-09 12:33 UTC, rafaellehmkuhl commented on core/services/ardupilot_manager/mavlink_proxy/MAVProxy.py
> +        filtered_endpoints = [endpoint for endpoint in self.endpoints() if endpoint.enabled is True]
Definitely.

2021-12-09 17:25 UTC, patrickelectric reviewed
Is there a reason to not squash 
126e62859fa84a9a82304bbc897207c416999963
f7a3b9353f2007fa1d6bbfb946e5fb730e3f93cd
?

2021-12-09 17:55 UTC, patrickelectric approved these changes

2021-12-09 19:08 UTC, merged