Add settings system on frontend
bluerobotics/companion-docker pull request #709
Opened 2021-12-16 18:34 UTC by patrickelectric

- Fix #630

2021-12-16 19:36 UTC, Williangalvani commented
lol. what's up with CI this time? :man_facepalming:

2021-12-16 19:48 UTC, patrickelectric commented
Probably related:
- https://github.com/samuelcolvin/pydantic/issues/3528

2021-12-17 13:23 UTC, rafaellehmkuhl requested changes
Cool! 🐠

2021-12-17 13:23 UTC, rafaellehmkuhl commented on core/frontend/src/store/settings.ts
> +  })
Strange indent. How that passed?

2022-01-05 16:39 UTC, patrickelectric commented on core/frontend/src/store/settings.ts
> +  })
Done.

2022-01-07 18:13 UTC, patrickelectric commented on core/frontend/src/libs/settings.ts
> +  }
When storage is updated (or set is used), the get will be called automatically.

2022-01-10 11:36 UTC, rafaellehmkuhl approved these changes

2022-01-10 11:42 UTC, merged